name: FightSession
version: 1.3
description: Fight Session is a plugin that engage players in a « fight mode » when they hit each other and prevents them
   from running away using commands to teleport or if they disconnect during the combat time it will kill them.
author: Bletrazer
api-version: 1.17
main: fr.bletrazer.fightsession.Main
commands:
   fightsession:
      description: Principal command.
      aliases:
      - fight
      - fights
      - fs
permissions:
   fightsession.group.admin:
      description: All permissions of the plugin.
      op: true
      children:
         fightsession.reload: true
         fightsession.help: true
         fightsession.time: true
         fightsession.targets: true

   fightsession.group.player:
      description: Permissions help, targets and time (for players).
      default: true
      children:
         fightsession.help: true
         fightsession.time: true
         fightsession.targets: true

   fightsession.reload:
      description: Needed to reload the plugin.
   fightsession.help:
      description: Needed to view the help (/help) message.
   fightsession.time:
      description: Needed to view the time left when in fight.
   fightsession.targets:
      description: Needed to view the targets when in fight.